on:
  push:
    paths:
      - '**/collection.xml'
      - '**/resource.xml'
      - '.github/workflows/build.yml'
  workflow_dispatch:
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
              "id": "softalks",
              "username": "${{ secrets.GITHUB_TOKEN }}",
              "password": "${{ secrets.GITHUB_TOKEN }}" 
            }, {
              "id": "archetype",
              "username": "${{ secrets.GITHUB_TOKEN }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: main
        run: |
          echo "<source-code>"
          cat --number $(readlink -f $0)
          echo "</source-code>"
          if test -z "${{ steps.files.outputs.removed }}"; then
            echo "No files removed (OK)"
          else
            exit 1001
          fi
          if test -z "${{ steps.files.outputs.renamed }}"; then
            echo "No files renamed (OK)"
          else
            exit 1002
          fi
          build () {
            echo "type of change: " $1
            for changed_file in $2; do
              parent_dir="$(dirname -- "$(readlink -f -- "$changed_file")")"
              cd $parent_dir
              wget http://agencia-tributaria.github.io/resource_type/pom.xml
              wget http://agencia-tributaria.github.io/resource_type/org.apache.maven-archetype-plugin.input.xml 
              cat pom.xml
              mvn archetype:generate --batch-mode --update-snapshots -DarchetypeGroupId=agencia-tributaria -DarchetypeArtifactId=entidad -DarchetypeVersion=1.0-SNAPSHOT -DgroupId=agencia-tributaria -DgroupIdPat=${{ secrets.GITHUB_TOKEN }} -DartifactId=adts-hello -Dversion=1.0-SNAPSHOT -Dpackage=es.aeat.adts -Dclass=Hello
            done
          }
          if test -z "${{ steps.files.outputs.added }}"; then
            echo "No files added"
          else
            build "added" ${{ steps.files.outputs.added }}
          fi
          if test -z "${{ steps.files.outputs.modified }}"; then
            echo "No files modified"
          else
            build "modified" ${{ steps.files.outputs.modified }}
          fi
          cd adts-hello/src/main/java/es/aeat/adts
          pwd
          echo "Hello, World!"
          cat --number Hello.java
          cat --number test.xml
          tree
