on:
  push:
    paths:
      - '**/resource_type.xml'
      - '.github/workflows/build.yml'
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
              "id": "downstream-repository",
              "username": "${{ secrets.GITHUB_TOKEN }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          if test -z "${{ steps.files.outputs.removed }}"; then
            echo "No files removed (OK)"
          else
            exit 1
          fi
          if test -z "${{ steps.files.outputs.renamed }}"; then
            echo "No files renamed (OK)"
          else
            exit 1
          fi
          echo "test 1"
          added = "${{ steps.files.outputs.added }}"
          echo "test 2"
          if test -z "$added"; then
            echo "test 3.1"
            echo "No files added"
          else
            echo "test 3.2"
            build("added", $added)
          fi
          modified = ${{ steps.files.outputs.modified }}
          if test -z "$modified"; then
            echo "No files modified"
          else
            build("modified", $modified)
          fi
          build () {
            echo "type of change: " $1
            for changed_file in $2; do
              parent_dir="$(dirname -- "$(readlink -f -- "$changed_file")")"
              echo "folder: " $parent_dir
              # mvn archetype:generate --batch-mode --update-snapshots -DarchetypeGroupId=agencia-tributaria -DarchetypeArtifactId=entidad -DarchetypeVersion=1.0-SNAPSHOT ${changed_file}."
            done
          }
